### ISSUE TITLE
Is it possible to communicate between two renderer windows?

### ISSUE THREAD

**Issue by kvt** [krimlabs/eiphop#1]
For my project, I want to send request to hidden renderer process. we have database layer in hidden window.

**Comment by shivekkhurana** [comment]
Can you please elaborate on the issue? 

From what I understand (and correct me if I'm wrong), you need to send the same data to two windows. That's out of the current scope of eiphop and you'll have to consume IPC apis directly.

**Comment by kvt** [comment]
Thanks for quick reply. We have one main process, and two renderer processes(browser windows), one renderer process is for UI and other for database. so I want to send request from one browser window to other browser window(which is hidden) instead of main process.

**Comment by shivekkhurana** [comment]
Okay. I don't know if that is a legit operation at IPC level. 

But you can easily do that via the main process (eiphop will be useless in your specific case).

Instead of making the renderer process talk directly to each other, setup ipc channel in main process that helps the two renderers share data.

**Comment by kvt** [comment]
Okay, I modified code for my requirement, now its working fine. Thanks.

**Comment by hadeeb** [comment]
@kvt If it is not too much to ask, can you please share your setup?
