### ISSUE TITLE
Cannot read property 'dfd' of undefined

### ISSUE THREAD

**Issue by FadyQJ** [krimlabs/eiphop#14]
Hello,

I am using eiphop and whenever I call the emit function I get the following error:

renderer.js:111 Uncaught TypeError: Cannot read property 'dfd' of undefined
  at EventEmitter.<anonymous> (renderer.js:111)
  at EventEmitter.emit (events.js:199)

This is my actions variable:
```javascript
const actions = {  
  getCategories: async (req, res) => {
    var data = openJSON(CONFIG_DIR + path.sep + CAT_FILE);
    if (data === undefined)
      res.send({ categories: [] });
    else
      res.send({ categories: data });
  }
}
```

I'm calling a function to setup the actions using:
```javascript
module.exports = {
  setupAPI: function(electron) {
    setupMainHandler(electron, {...actions});
  }
}
```

And finally in jsx:
```javascript
emit('getCategories').then((res) => { this.setState({ categories: res.categories });  });
```

**Comment by shivekkhurana** [comment]
Hi @FadyQJ 

The `setupMainHandler` needs to be called in the main process. Since you are exposing it in a map with key `setupAPI`, did you call `setupAPI` function in the main process ?

**Comment by FadyQJ** [comment]
Hello @shivekkhurana and thank you for your reply.

Yes, I have in the main.js
```javascript
const API = require('./api.js');
// some code
API.setupAPI(electron);
```

I even tried adding the 'API.setupAPI(electron);' inside the `createWindow` that is called using `app.on('ready', createWindow)`

I also added console log in my setupAPI function and it is being called as expected.
Everything is working fine, emit is working fully, I am just receiving this warning for some reason.

Btw, every emit function I call I receive this error.
Can I have an idea of why this is happening? Maybe there's something I missed, I tried some methods to see if I am doing something wrong but no luck.

**Comment by shivekkhurana** [comment]
I'm hoping that you've setup the `frontendListener` correctly.

If so, can you share a sample repo where this bug is present? It'll help me figure what's wrong since I'm not able to reproduce your problem locally.

**Comment by FadyQJ** [comment]
I created a small repo with the code I'm using, and added you as a collaborator.
I omitted the C++ library that I am working on, it should not affect anything, sorry but I am unable to share it.

**Comment by shivekkhurana** [comment]
No problem about the private repo. I'll clone it and see what's up. Thanks.

**Comment by shivekkhurana** [comment]
Hi @FadyQJ 

After reviewing your repo, I observed that you called `setupFrontendListener` in all namespaces where `emit` was being called.  (in Categories.js and Import.js)

**This is not the correct way. Instead you should call `setupFrontendListener` only once in the index.js file (or App.js in your case).**

This is because all `setupFrontendListener` creates a singleton object which is used to track requests. By calling `setupFrontendListner` multiple times, you created multiple copies of the singleton. This sounds so wrong already.

The request generated from handler created by App.js, but response was caught by handler created by Categories.js (because `setupFrontendListener` overwrote the handler in subsequent call). 

If you get rid of multiple `setupFrontendListener` calls, the error will go away. 

Keep me updated here.

**Comment by FadyQJ** [comment]
Hello @shivekkhurana

That resolved the issue, I feel so stupid XD

Sorry for wasting your time.
