### ISSUE TITLE
Q: Why eiphop instead of invoke and handle?

### ISSUE THREAD

**Issue by brumik** [krimlabs/eiphop#63]
After getting more familiar with electron, I have a question: 
For me the [`ipcMain.handle`](https://www.electronjs.org/docs/latest/api/ipc-main#ipcmainhandlechannel-listener) and [`ipcRenderer.invoke`](https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrendererinvokechannel-args) seems to do the same thing that eiphop wants to achieve. Is there a reason why is eiphop better?

Thank you for the explanation.

**Comment by shivekkhurana** [comment]
I wrote a blog post to answer this question: https://medium.com/@shivekkhurana/introducing-eiphop-an-electron-ipc-wrapper-good-fit-for-react-apps-50de6826a47e

Did you read it ?

**Comment by brumik** [comment]
I did, but seemingly handle and invoke does the same exact thing. Introducing `Promise` based communication between `main` and `renderer`.

**Comment by shivekkhurana** [comment]
If you don't use Eiphop, you will have to handle promises each time you make a request to the backend. N request will lead to N promises, that might resolve in any order.

If you do use Eiphop, you will have a queue like interface to make requests and receive responses. For N requests made, you will only have one handler. The promises will still be resolved out of order (its not FIFO, because tasks are async), but you will only have to deal with one response at a time. 

The insight is to push side-effects to the edge of your system. Without Eiphop, your system will have internal side-effects. 
If you come from a React background, you can think of Eiphop as redux.
